'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'hi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  hi: {
    // Navigation
    "dashboard": "डैशबोर्ड",
    "disease": "रोग पहचान",
    "weather": "मौसम",
    "market": "मंडी भाव",
    "schemes": "योजनाएं",
    "profile": "प्रोफाइल",
    "alerts": "अलर्ट",
    "yield": "उत्पादन विश्लेषण",
    "machinery": "मशीनरी किराया",
    "voice": "आवाज़ सहायक",
    "chatbot": "चैट सहायक",
    
    // Global Labels
    "back": "पीछे जाएं",
    "search": "खोजें...",
    "loading": "लोड हो रहा है...",
    "error": "त्रुटि",
    "cancel": "रद्द करें",
    "submit": "सुरक्षित करें",
    "fresh": "नया",
    
    // Home Page
    "home_title": "खेती को बनाएं Smart & Profitable",
    "home_subtitle": "रोग पहचान · मौसम जानकारी · मंडी भाव · AI सलाह — सब कुछ एक जगह।",
    "home_badge": "AI-संचालित कृषि मंच",
    "home_start_cta": "स्मार्ट खेती शुरू करें",
    "home_ask_cta": "AI से पूछें",
    "home_farmers_connected": "किसान जुड़े",
    "home_accuracy": "Accuracy",
    "home_crops_covered": "फसलें Cover",
    "home_latest_updates": "ताज़ा अपडेट",
    "home_ticker_1": "🌧️ अगले 3 दिन बारिश की संभावना — सिंचाई रोकें",
    "home_ticker_2": "💰 PM Kisan की नई किस्त जारी — अभी चेक करें",
    "home_ticker_3": "🐛 पूर्वी UP में टिड्डी अलर्ट — सावधान रहें",
    "home_ticker_4": "📈 गेहूं का MSP ₹2,275/क्विंटल — बेचने का सही समय",
    "home_our_services": "हमारी सेवाएं <span>🌾</span>",
    "home_services_sub": "किसान की हर ज़रूरत के लिए AI-powered tools",
    "home_how_it_works": "कैसे करें Use? <span>🤔</span>",
    "home_step1_title": "फोटो लें",
    "home_step1_desc": "फसल या मिट्टी की photo खींचें",
    "home_step2_title": "Upload करें",
    "home_step2_desc": "Photo हमारे AI को भेजें",
    "home_step3_title": "AI Analyze",
    "home_step3_desc": "AI कुछ सेकंड में analyze करता है",
    "home_step4_title": "सलाह पाएं",
    "home_step4_desc": "इलाज और सुझाव हिंदी में पाएं",
    "home_service_disease_desc": "फोटो से तुरंत पहचानें फसल की बीमारी",
    "home_service_soil_desc": "मिट्टी का प्रकार और उर्वरता जानें",
    "home_service_weather_desc": "7-दिन का मौसम और खेती सलाह",
    "home_service_ai_desc": "24/7 कृषि विशेषज्ञ AI चैटबॉट",
    "home_service_market_desc": "लाइव मंडी भाव और ट्रेंड्स",
    "home_service_machinery_desc": "नज़दीकी ट्रैक्टर और मशीन बुक करें",
    "home_service_schemes_desc": "PM Kisan, Fasal Bima सब एक जगह",
    "home_service_voice_desc": "बोलकर पूछें, AI जवाब देगा",
    "home_testimonials": "किसानों की बात <span>💬</span>",
    "home_testimonial_1_text": "\"Krishi AI ने मेरी गेहूं की फसल बचाई। रोग पहचान से 3 दिन पहले ही पता चल गया।\"",
    "home_testimonial_1_author": "रमेश सिंह",
    "home_testimonial_1_sub": "किसान, UP",
    "home_testimonial_2_text": "\"मंडी भाव feature से पता चला कि मेरे धान को 20% ज़्यादा rate मिल सकता है।\"",
    "home_testimonial_2_author": "सुनीता कुमारी",
    "home_testimonial_2_sub": "किसान, Bihar",
    "home_testimonial_3_text": "\"Voice feature बहुत अच्छा है, पढ़ना नहीं आता तो बोलकर पूछ लेता हूं।\"",
    "home_testimonial_3_author": "मोहन पटेल",
    "home_testimonial_3_sub": "किसान, MP",
    "home_cta_title": "आज ही शुरू करें — <span>मुफ़्त में!</span>",
    "home_cta_desc": "50,000+ किसान पहले से use कर रहे हैं",
    "home_cta_btn": "अभी शुरू करें",

    // Dashboard Page
    "dash_title": "मेरा डैशबोर्ड",
    "dash_subtitle": "नमस्ते, {name}! आज का सारांश देखें।",
    "dash_hello_farmer": "किसान जी",
    "dash_today_summary": "आज का सारांश देखें।",
    "dash_crop_health": "फसल स्वास्थ्य",
    "dash_crop_healthy": "Good",
    "dash_crop_health_sub": "85% स्वस्थ",
    "dash_status_safe": "✓ सुरक्षित",
    "dash_weather_loc": "मौसम",
    "dash_weather_irrigate": "⚠ सिंचाई रोकें",
    "dash_weather_normal": "🌤️ सामान्य",
    "dash_mandi_today": "आज मंडी भाव",
    "dash_per_quintal": "प्रति क्विंटल",
    "dash_active_alerts": "सक्रिय अलर्ट",
    "dash_alerts_new": "New",
    "dash_alerts_view": "देखें",
    "dash_crop_yield": "फसल उत्पादन (Quintal)",
    "dash_revenue_vs_expense": "कमाई vs खर्च",
    "dash_revenue": "कमाई",
    "dash_expense": "खर्च",
    "dash_ai_advisory": "AI सलाह — आज की",
    "dash_recent_checks": "हालिया जांच",
    "dash_new_check": "नई जांच",
    "dash_no_checks": "अभी तक कोई जांच नहीं हुई",
    "dash_check_now": "जांच करें",
    "dash_5day_weather": "मौसम — 5 दिन",
    "dash_weather_details": "विस्तार",
    "dash_crop_progress": "फसल प्रगति",
    "dash_full_report": "पूरी रिपोर्ट",

    // Page: Yield
    "yield_title": "Yield & Profit Analysis",
    "yield_sub": "अपनी फसल के उत्पादन और मुनाफ़े का पूरा विश्लेषण",
    "total_yield": "कुल उत्पादन",
    "total_revenue": "कुल कमाई",
    "total_expenses": "कुल खर्च",
    "net_profit": "शुद्ध मुनाफ़ा",
    "this_season": "इस सीजन",
    "from_mandi": "मंडी से",
    "seeds_fertilizer": "बीज, खाद, मज़दूरी",
    "net_profit_sub": "Net Profit",
    "last_vs_this": "पिछले साल vs इस साल",
    "last_year": "पिछला साल",
    "this_year_ai": "इस साल (AI के साथ)",
    "production": "उत्पादन",
    "revenue": "कमाई",
    "expenses": "खर्च",
    "profit": "मुनाफ़ा",
    "extra_profit_banner": "Krishi AI की मदद से अतिरिक्त मुनाफ़ा!",
    "monthly_production": "महीनेवार उत्पादन",
    "crop_contribution": "फसल योगदान",
    "record_history": "फसल रिकॉर्ड इतिहास",
    "crop_name": "फसल",
    "amount": "मात्रा",
    "date": "तारीख",
    "add_record": "नया रिकॉर्ड जोड़ें",
    "post_ad": "सुरक्षित करें",
    "yield_add_title": "नया उत्पादन और खर्च दर्ज करें",
    "yield_amount_q": "मात्रा (Quintal)",
    "yield_date_label": "तारीख",
    "yield_saving": "बचाया जा रहा है...",
    "yield_extra_profit_text": "Krishi AI की मदद से {profit} अतिरिक्त मुनाफ़ा इस साल!",
    
    // Page: Machinery
    "machinery_title": "मशीनरी किराया",
    "machinery_sub": "अपने नज़दीक ट्रैक्टर, हार्वेस्टर और अन्य मशीनें किराए पर लें",
    "all_machines": "सभी मशीनें",
    "tractor": "ट्रैक्टर",
    "harvester": "हार्वेस्टर",
    "rotavator": "रोटावेटर",
    "sprayer": "स्प्रेयर",
    "thresher": "थ्रेशर",
    "available": "उपलब्ध",
    "booked": "बुक",
    "per_day": "/दिन",
    "rent_now": "Rent Now",
    "add_machine": "मशीन जोड़ें",
    "owner": "मालिक का नाम",
    "mobile": "मोबाइल नंबर",
    "machinery_search_placeholder": "मशीन खोजें...",
    "machinery_search_btn": "खोजें",
    "machinery_no_results": "आपके क्षेत्र में कोई मशीन नहीं मिली",
    "machinery_modal_title": "नई मशीन जोड़ें",
    "machinery_owner_name": "मालिक का नाम (Owner Name)",
    "machinery_post_btn": "विज्ञापन पोस्ट करें",
    "machinery_posting": "जोड़ा जा रहा है...",
    "machinery_rent_success": "सफलतापूर्वक बुक किया गया: {name}\nमालिक से संपर्क करें: {owner} ({mobile})",

    // Disease Page
    "disease_title_page": "फसल रोग पहचान",
    "disease_sub_page": "फसल की photo upload करें — AI तुरंत रोग बताएगा",
    "disease_dropzone_title": "Photo यहाँ डालें",
    "disease_dropzone_desc": "या नीचे से choose करें",
    "disease_choose_btn": "Photo चुनें / Camera",
    "disease_crop_label": "फसल का नाम",
    "disease_select_crop": "-- फसल चुनें --",
    "disease_symptoms_label": "लक्षण बताएं (Optional)",
    "disease_symptoms_placeholder": "जैसे: पत्तियों पर पीले दाग, तना सड़ रहा है...",
    "disease_submit_btn": "AI से जांच करवाएं",
    "disease_scanning": "AI जांच कर रहा है...",
    "disease_scanning_wait": "कृपया रुकें, कुछ सेकंड लगेंगे",
    "disease_empty_title": "अभी तक कोई जांच नहीं",
    "disease_empty_desc": "Photo upload करके AI से फसल की जांच करवाएं",
    "disease_tip_clean": "साफ, close-up photo लें",
    "disease_tip_light": "अच्छी रोशनी में photo लें",
    "disease_tip_part": "रोगी पत्ती / तना दिखाएं",
    "disease_cause": "कारण",
    "disease_treatment": "इलाज",
    "disease_prevention": "रोकथाम",
    "disease_warning_disclaimer": "चेतावनी: यह एक AI सलाह है। उर्वरक या कीटनाशक छिड़काव से पहले कृपया अपने स्थानीय कृषि विस्तार अधिकारी या विशेषज्ञ से सलाह लें।",

    // Weather Page
    "weather_title_page": "मौसम जानकारी",
    "weather_sub_page": "अपने खेत का मौसम देखें और खेती की सही योजना बनाएं",
    "weather_search_placeholder": "शहर या जिला टाइप करें...",
    "weather_search_btn": "खोजें",
    "weather_auto_btn": "Auto",
    "weather_humidity": "नमी",
    "weather_wind": "हवा",
    "weather_pressure": "दबाव",
    "weather_visibility": "Visibility",
    "weather_forecast_title": "7-दिन का पूर्वानुमान",
    "weather_advisory_title": "मौसम के अनुसार खेती सलाह",
    "weather_empty_title": "मौसम लोड नहीं हो पाया",
    "weather_empty_desc": "कृपया पुनः प्रयास करें या कोई अन्य शहर / जिला टाइप करें।",

    // Market Page
    "market_title_page": "मंडी भाव",
    "market_sub_page": "आज के लाइव बाज़ार भाव — सही समय पर बेचें और कमाएं",
    "market_search_placeholder": "फसल खोजें...",
    "market_all_states": "सभी राज्य",
    "market_filter_btn": "देखें",
    "market_last_updated": "अंतिम अपडेट: आज सुबह 9:00 बजे",
    "market_empty_title": "कोई मंडी भाव नहीं मिला",
    "market_empty_desc": "कृपया भिन्न फसल का नाम या फ़िल्टर का चयन करें।",

    // Schemes Page
    "schemes_title_page": "सरकारी योजनाएं",
    "schemes_sub_page": "किसानों के लिए सरकारी योजनाएं — सब एक जगह",
    "schemes_search_placeholder": "योजना का नाम या लाभ खोजें...",
    "schemes_search_btn": "खोजें",
    "schemes_all": "सभी",
    "schemes_cat_financial": "💰 वित्तीय",
    "schemes_cat_insurance": "🛡️ बीमा",
    "schemes_cat_organic": "🌿 जैविक",
    "schemes_cat_technology": "📱 तकनीकी",
    "schemes_empty_title": "कोई सरकारी योजना नहीं मिली",
    "schemes_empty_desc": "कृपया भिन्न खोज शब्द का प्रयास करें।",
    "schemes_apply_btn": "Apply करें",
    "schemes_learn_more": "और जानें",

    // Profile Page
    "profile_title_page": "मेरी प्रोफाइल",
    "profile_sub_page": "अपनी जानकारी अपडेट करें",
    "profile_step1": "व्यक्तिगत",
    "profile_step2": "खेत की जानकारी",
    "profile_step3": "फसलें",
    "profile_personal_title": "व्यक्तिगत जानकारी",
    "profile_photo_change": "Photo Change करें",
    "profile_name": "पूरा नाम",
    "profile_name_placeholder": "आपका नाम",
    "profile_mobile": "मोबाइल नंबर",
    "profile_mobile_placeholder": "10 अंक का नंबर",
    "profile_village": "गाँव / शहर",
    "profile_village_placeholder": "गाँव का नाम",
    "profile_district": "जिला",
    "profile_district_placeholder": "जिला",
    "profile_state": "राज्य",
    "profile_language": "भाषा",
    "profile_next": "अगला",
    "profile_prev": "पिछला",
    "profile_save": "सेव करें",
    "profile_farm_title": "खेत की जानकारी",
    "profile_land_acres": "जमीन (एकड़ में)",
    "profile_land_placeholder": "जैसे: 5",
    "profile_irrigation": "सिंचाई का तरीका",
    "profile_soil_type": "मिट्टी का प्रकार",
    "profile_own_tractor": "खुद का ट्रैक्टर है?",
    "profile_tractor_yes": "हाँ",
    "profile_tractor_no": "नहीं",
    "profile_crops_title": "मुख्य फसलें",

    // Voice Page
    "voice_title_page": "Voice Advisory",
    "voice_sub_page": "बोलकर पूछें — AI हिंदी में जवाब देगा",
    "voice_instruction_default": "माइक बटन दबाएं और बोलें",
    "voice_instruction_listening": "सुन रहा हूं...",
    "voice_instruction_analyzing": "AI उत्तर तैयार कर रहा है...",
    "voice_speak_again": "फिर से सुनें",
    "voice_ai_response": "AI का जवाब",
    "voice_you_said": "आपने कहा:",
    "voice_tips_title": "🎙️ ऐसे पूछें:",

    // Chatbot Page
    "chatbot_title_page": "Krishi AI सहायक",
    "chatbot_status": "Online — हमेशा उपलब्ध",
    "chatbot_welcome": "नमस्ते! 🌾 मैं आपका AI कृषि सहायक हूं। आप मुझसे पूछ सकते हैं:",
    "chatbot_welcome_item1": "🌱 फसल रोग और इलाज",
    "chatbot_welcome_item2": "💧 सिंचाई और खाद",
    "chatbot_welcome_item3": "💰 मंडी भाव और बेचने की सलाह",
    "chatbot_welcome_item4": "☁️ मौसम और खेती टिप्स",
    "chatbot_welcome_item5": "📋 सरकारी योजनाएं",
    "chatbot_placeholder": "संदेश लिखें... (Hindi / English)",
    "chatbot_listening": "सुन रहा हूं...",
    
    // Page: Alerts
    "alerts_title": "अलर्ट & सूचनाएं",
    "alerts_sub": "ज़रूरी जानकारी जो आपको जाननी चाहिए",
    "all": "सभी",
    "danger": "🔴 ख़तरा",
    "warning": "🟡 सावधान",
    "info": "🔵 जानकारी",
    "no_alerts": "कोई सक्रिय अलर्ट नहीं है",
    "check_now": "जांच करें",
    "check_scheme": "चेक करें",
    "check_weather": "मौसम देखें",
    
    // Footer
    "footer_tagline": "किसान की हर ज़रूरत, एक जगह।",
    "privacy": "प्राइवेसी पॉलिसी",
    "help": "सहायता केंद्र",
    "designed_for": "Designed for Indian Farmers 🌾",

    // Crop translations
    "crop_गेहूं": "गेहूं",
    "crop_धान": "धान",
    "crop_मक्का": "मक्का",
    "crop_सरसों": "सरसों",
    "crop_गन्ना": "गन्ना",
    "crop_टमाटर": "टमाटर",
    "crop_आलू": "आलू",
    "crop_प्याज": "प्याज",
    "crop_मिर्च": "मिर्च",
    "crop_चना": "चना",
    "crop_सोयाबीन": "सोयाबीन",
    "crop_कपास": "कपास",

    // Soil translations
    "काली मिट्टी": "काली मिट्टी",
    "लाल मिट्टी": "लाल मिट्टी",
    "बलुई मिट्टी": "बलुई मिट्टी",
    "दोमट मिट्टी": "दोमट मिट्टी",
    "जलोढ़ मिट्टी": "जलोढ़ मिट्टी",

    // Irrigation translations
    "नहर (Canal)": "नहर (Canal)",
    "बोरवेल (Borewell)": "बोरवेल (Borewell)",
    "वर्षा (Rainwater)": "वर्षा (Rainwater)",
    "Drip Irrigation": "Drip Irrigation"
  },
  en: {
    // Navigation
    "dashboard": "Dashboard",
    "disease": "Disease Detect",
    "weather": "Weather",
    "market": "Mandi Rates",
    "schemes": "Schemes",
    "profile": "Profile",
    "alerts": "Alerts & Inbox",
    "yield": "Yield Analysis",
    "machinery": "Rent Machinery",
    "voice": "Voice Assistant",
    "chatbot": "Chat Assistant",
    
    // Global Labels
    "back": "Back",
    "search": "Search...",
    "loading": "Loading...",
    "error": "Error",
    "cancel": "Cancel",
    "submit": "Submit",
    "fresh": "Fresh",
    
    // Home Page
    "home_title": "Make farming Smart & Profitable",
    "home_subtitle": "Disease Detection · Weather Advisory · Mandi Rates · AI Support — All in one place.",
    "home_badge": "AI-Powered Farming Platform",
    "home_start_cta": "Start Farming Smart",
    "home_ask_cta": "Ask AI",
    "home_farmers_connected": "Farmers Connected",
    "home_accuracy": "Accuracy",
    "home_crops_covered": "Crops Covered",
    "home_latest_updates": "Latest Updates",
    "home_ticker_1": "🌧️ Rain expected in next 3 days — stop irrigation",
    "home_ticker_2": "💰 New PM Kisan installment released — check now",
    "home_ticker_3": "🐛 Locust alert in Eastern UP — stay alert",
    "home_ticker_4": "📈 Wheat MSP ₹2,275/quintal — right time to sell",
    "home_our_services": "Our Services <span>🌾</span>",
    "home_services_sub": "AI-powered tools for every farmer's needs",
    "home_how_it_works": "How it works? <span>🤔</span>",
    "home_step1_title": "Take Photo",
    "home_step1_desc": "Take a photo of crop or soil",
    "home_step2_title": "Upload",
    "home_step2_desc": "Send photo to our AI",
    "home_step3_title": "AI Analysis",
    "home_step3_desc": "AI analyzes in a few seconds",
    "home_step4_title": "Get Advice",
    "home_step4_desc": "Get treatment and suggestions instantly",
    "home_service_disease_desc": "Instantly detect crop disease from photos",
    "home_service_soil_desc": "Know soil type and fertility",
    "home_service_weather_desc": "7-day weather and farming advice",
    "home_service_ai_desc": "24/7 agricultural expert AI chatbot",
    "home_service_market_desc": "Live market rates and trends",
    "home_service_machinery_desc": "Book nearby tractors and machinery",
    "home_service_schemes_desc": "PM Kisan, Fasal Bima all in one place",
    "home_service_voice_desc": "Ask by speaking, AI will answer",
    "home_testimonials": "Farmers' Voice <span>💬</span>",
    "home_testimonial_1_text": "\"Krishi AI saved my wheat crop. Found the disease 3 days in advance.\"",
    "home_testimonial_1_author": "Ramesh Singh",
    "home_testimonial_1_sub": "Farmer, UP",
    "home_testimonial_2_text": "\"Mandi rates feature showed my paddy could get 20% higher price.\"",
    "home_testimonial_2_author": "Sunita Kumari",
    "home_testimonial_2_sub": "Farmer, Bihar",
    "home_testimonial_3_text": "\"Voice feature is very good, I can just speak if I don't know how to read.\"",
    "home_testimonial_3_author": "Mohan Patel",
    "home_testimonial_3_sub": "Farmer, MP",
    "home_cta_title": "Start Today — <span>For Free!</span>",
    "home_cta_desc": "50,000+ Farmers are already using it",
    "home_cta_btn": "Start Now",

    // Dashboard Page
    "dash_title": "My Dashboard",
    "dash_subtitle": "Hello, {name}! View today's summary.",
    "dash_hello_farmer": "Farmer",
    "dash_today_summary": "View today's summary.",
    "dash_crop_health": "Crop Health",
    "dash_crop_healthy": "Good",
    "dash_crop_health_sub": "85% healthy",
    "dash_status_safe": "✓ Safe",
    "dash_weather_loc": "Weather",
    "dash_weather_irrigate": "⚠ Stop Irrigation",
    "dash_weather_normal": "🌤️ Normal",
    "dash_mandi_today": "Today's Mandi Rates",
    "dash_per_quintal": "per quintal",
    "dash_active_alerts": "Active Alerts",
    "dash_alerts_new": "New",
    "dash_alerts_view": "View",
    "dash_crop_yield": "Crop Yield (Quintal)",
    "dash_revenue_vs_expense": "Revenue vs Expenses",
    "dash_revenue": "Revenue",
    "dash_expense": "Expenses",
    "dash_ai_advisory": "AI Advisory — Today's",
    "dash_recent_checks": "Recent Checks",
    "dash_new_check": "New Check",
    "dash_no_checks": "No inspections done yet",
    "dash_check_now": "Check Now",
    "dash_5day_weather": "Weather — 5 Days",
    "dash_weather_details": "Details",
    "dash_crop_progress": "Crop Progress",
    "dash_full_report": "Full Report",

    // Page: Yield
    "yield_title": "Yield & Profit Analysis",
    "yield_sub": "Complete analysis of your crop production and profits",
    "total_yield": "Total Yield",
    "total_revenue": "Total Revenue",
    "total_expenses": "Total Expenses",
    "net_profit": "Net Profit",
    "this_season": "This Season",
    "from_mandi": "From Mandi",
    "seeds_fertilizer": "Seeds, Fertilizer, Labor",
    "net_profit_sub": "Net Profit",
    "last_vs_this": "Last Year vs This Year",
    "last_year": "Last Year",
    "this_year_ai": "This Year (with AI)",
    "production": "Production",
    "revenue": "Revenue",
    "expenses": "Expenses",
    "profit": "Profit",
    "extra_profit_banner": "Extra profit earned this year using Krishi AI!",
    "monthly_production": "Monthly Production",
    "crop_contribution": "Crop Contribution",
    "record_history": "Crop Records History",
    "crop_name": "Crop",
    "amount": "Amount",
    "date": "Date",
    "add_record": "Add New Record",
    "post_ad": "Save Record",
    "yield_add_title": "Record New Production & Expenses",
    "yield_amount_q": "Amount (Quintal)",
    "yield_date_label": "Date",
    "yield_saving": "Saving...",
    "yield_extra_profit_text": "₹{profit} extra profit earned this year using Krishi AI!",
    
    // Page: Machinery
    "machinery_title": "Rent Machinery",
    "machinery_sub": "Rent tractors, harvesters and other machinery near you",
    "all_machines": "All Machinery",
    "tractor": "Tractor",
    "harvester": "Harvester",
    "rotavator": "Rotavator",
    "sprayer": "Sprayer",
    "thresher": "Thresher",
    "available": "Available",
    "booked": "Rented",
    "per_day": "/day",
    "rent_now": "Rent Now",
    "add_machine": "Add Machine",
    "owner": "Owner Name",
    "mobile": "Mobile Number",
    "machinery_search_placeholder": "Search machinery...",
    "machinery_search_btn": "Search",
    "machinery_no_results": "No machinery found in your area",
    "machinery_modal_title": "Add New Machinery",
    "machinery_owner_name": "Owner Name",
    "machinery_post_btn": "Post Advertisement",
    "machinery_posting": "Posting...",
    "machinery_rent_success": "Booked successfully: {name}\nContact owner: {owner} ({mobile})",

    // Disease Page
    "disease_title_page": "Crop Disease Detection",
    "disease_sub_page": "Upload crop photo — AI will diagnose instantly",
    "disease_dropzone_title": "Drop Photo Here",
    "disease_dropzone_desc": "or choose from device",
    "disease_choose_btn": "Choose Photo / Camera",
    "disease_crop_label": "Crop Name",
    "disease_select_crop": "-- Select Crop --",
    "disease_symptoms_label": "Describe Symptoms (Optional)",
    "disease_symptoms_placeholder": "E.g., Yellow spots on leaves, stem rotting...",
    "disease_submit_btn": "Diagnose with AI",
    "disease_scanning": "AI is analyzing...",
    "disease_scanning_wait": "Please wait, this will take a few seconds",
    "disease_empty_title": "No diagnosis yet",
    "disease_empty_desc": "Upload a photo to get crop disease diagnosis from AI",
    "disease_tip_clean": "Take a clean, close-up photo",
    "disease_tip_light": "Ensure good lighting",
    "disease_tip_part": "Show infected leaves/stem",
    "disease_cause": "Cause",
    "disease_treatment": "Treatment",
    "disease_prevention": "Prevention",
    "disease_warning_disclaimer": "Warning: This is an AI advisory report. Please consult your local agricultural extension officer or an agronomist before spraying fertilizers or pesticides.",

    // Weather Page
    "weather_title_page": "Weather Advisory",
    "weather_sub_page": "Check weather for your farm to plan daily activities",
    "weather_search_placeholder": "Type city or district...",
    "weather_search_btn": "Search",
    "weather_auto_btn": "Auto",
    "weather_humidity": "Humidity",
    "weather_wind": "Wind",
    "weather_pressure": "Pressure",
    "weather_visibility": "Visibility",
    "weather_forecast_title": "7-Day Forecast",
    "weather_advisory_title": "Weather Agricultural Advice",
    "weather_empty_title": "Weather data not loaded",
    "weather_empty_desc": "Please try again or search for another city/district.",

    // Market Page
    "market_title_page": "Mandi Rates",
    "market_sub_page": "Today's live market prices — sell at the right time and earn more",
    "market_search_placeholder": "Search crop...",
    "market_all_states": "All States",
    "market_filter_btn": "Filter",
    "market_last_updated": "Last updated: Today at 9:00 AM",
    "market_empty_title": "No market rates found",
    "market_empty_desc": "Please try searching for another crop or change filters.",

    // Schemes Page
    "schemes_title_page": "Government Schemes",
    "schemes_sub_page": "Government schemes for farmers — all in one place",
    "schemes_search_placeholder": "Search scheme name or benefit...",
    "schemes_search_btn": "Search",
    "schemes_all": "All",
    "schemes_cat_financial": "💰 Financial",
    "schemes_cat_insurance": "🛡️ Insurance",
    "schemes_cat_organic": "🌿 Organic",
    "schemes_cat_technology": "📱 Technical",
    "schemes_empty_title": "No schemes found",
    "schemes_empty_desc": "Please try searching for a different term.",
    "schemes_apply_btn": "Apply Now",
    "schemes_learn_more": "Learn More",

    // Profile Page
    "profile_title_page": "My Profile",
    "profile_sub_page": "Update your farming profile",
    "profile_step1": "Personal Details",
    "profile_step2": "Farm Details",
    "profile_step3": "Crops",
    "profile_personal_title": "Personal Information",
    "profile_photo_change": "Change Photo",
    "profile_name": "Full Name",
    "profile_name_placeholder": "Your Name",
    "profile_mobile": "Mobile Number",
    "profile_mobile_placeholder": "10-digit number",
    "profile_village": "Village / City",
    "profile_village_placeholder": "Village Name",
    "profile_district": "District",
    "profile_district_placeholder": "District",
    "profile_state": "State",
    "profile_language": "Language",
    "profile_next": "Next",
    "profile_prev": "Previous",
    "profile_save": "Save Details",
    "profile_farm_title": "Farm Information",
    "profile_land_acres": "Land Size (in Acres)",
    "profile_land_placeholder": "E.g. 5",
    "profile_irrigation": "Irrigation Method",
    "profile_soil_type": "Soil Type",
    "profile_own_tractor": "Do you own a tractor?",
    "profile_tractor_yes": "Yes",
    "profile_tractor_no": "No",
    "profile_crops_title": "Primary Crops",

    // Voice Page
    "voice_title_page": "Voice Advisory",
    "voice_sub_page": "Ask by speaking — AI will answer in English",
    "voice_instruction_default": "Press mic button and speak",
    "voice_instruction_listening": "Listening...",
    "voice_instruction_analyzing": "AI is finding answer...",
    "voice_speak_again": "Replay Answer",
    "voice_ai_response": "AI Response",
    "voice_you_said": "You said:",
    "voice_tips_title": "🎙️ Try asking:",

    // Chatbot Page
    "chatbot_title_page": "Krishi AI Assistant",
    "chatbot_status": "Online — Always Available",
    "chatbot_welcome": "Hello! 🌾 I am your AI agricultural helper. You can ask me about:",
    "chatbot_welcome_item1": "🌱 Crop diseases & treatments",
    "chatbot_welcome_item2": "💧 Irrigation & fertilization",
    "chatbot_welcome_item3": "💰 Mandi rates & selling advice",
    "chatbot_welcome_item4": "☁️ Weather & farming tips",
    "chatbot_welcome_item5": "📋 Government schemes",
    "chatbot_placeholder": "Type message... (Hindi / English)",
    "chatbot_listening": "Listening...",
    
    // Page: Alerts
    "alerts_title": "Alerts & Notifications",
    "alerts_sub": "Important information you need to know",
    "all": "All",
    "danger": "🔴 Danger",
    "warning": "🟡 Warning",
    "info": "🔵 Info",
    "no_alerts": "No active alerts at the moment",
    "check_now": "Inspect",
    "check_scheme": "Check Status",
    "check_weather": "Check Weather",
    
    // Footer
    "footer_tagline": "Everything a farmer needs, in one place.",
    "privacy": "Privacy Policy",
    "help": "Help Center",
    "designed_for": "Designed for Indian Farmers 🌾",

    // Crop translations
    "crop_गेहूं": "Wheat",
    "crop_धान": "Paddy",
    "crop_मक्का": "Maize",
    "crop_सरसों": "Mustard",
    "crop_गन्ना": "Sugarcane",
    "crop_टमाटर": "Tomato",
    "crop_आलू": "Potato",
    "crop_प्याज": "Onion",
    "crop_मिर्च": "Chilli",
    "crop_चना": "Gram",
    "crop_सोयाबीन": "Soybean",
    "crop_कपास": "Cotton",

    // Soil translations
    "काली मिट्टी": "Black Soil",
    "लाल मिट्टी": "Red Soil",
    "बलुई मिट्टी": "Sandy Soil",
    "दोमट मिट्टी": "Loamy Soil",
    "जलोढ़ मिट्टी": "Alluvial Soil",

    // Irrigation translations
    "नहर (Canal)": "Canal",
    "बोरवेल (Borewell)": "Borewell",
    "वर्षा (Rainwater)": "Rainwater",
    "Drip Irrigation": "Drip Irrigation",

    // Schemes translations
    "PM Kisan Samman Nidhi": "PM Kisan Samman Nidhi",
    "₹6,000 प्रति वर्ष, तीन किस्तों में सभी पात्र भूमिधारक किसान परिवारों को प्रत्यक्ष वित्तीय सहायता प्रदान करने के लिए केंद्र सरकार की योजना।": "Central government scheme to provide direct financial assistance of ₹6,000 per year in three installments to all eligible landholding farmer families.",
    "₹6,000/साल": "₹6,000/year",
    "PM Fasal Bima Yojana": "PM Fasal Bima Yojana",
    "प्राकृतिक आपदाओं, कीटों और रोगों के कारण फसलों के नुकसान पर वित्तीय सुरक्षा सुनिश्चित करने के लिए न्यूनतम प्रीमियम पर व्यापक फसल बीमा प्रदान करती है।": "Provides comprehensive crop insurance at minimum premium to ensure financial security against crop damage due to natural calamities, pests and diseases.",
    "फसल सुरक्षा (बीमा)": "Crop Protection (Insurance)",
    "Paramparagat Krishi Vikas Yojana": "Paramparagat Krishi Vikas Yojana",
    "जैविक खेती को बढ़ावा देने के लिए प्रति हेक्टेयर ₹50,000 की वित्तीय सहायता दी जाती है, जिसमें से 60% जैविक इनपुट (बीज, खाद) के लिए सीधा लाभ है।": "Financial assistance of ₹50,000 per hectare is provided to promote organic farming, out of which 60% is direct benefit for organic inputs (seeds, fertilizer).",
    "₹50,000/हेक्टेयर": "₹50,000/hectare",
    "कृषि यंत्रीकरण योजना (Sub-Mission on Agricultural Mechanization)": "Agricultural Mechanization Scheme (Sub-Mission on Agricultural Mechanization)",
    "किसानों को ट्रैक्टर, रोटावेटर, कल्टीवेटर और अन्य आधुनिक कृषि यंत्र खरीदने पर 40% से 80% तक की भारी सब्सिडी प्रदान की जाती है।": "Farmers are provided with massive subsidies ranging from 40% to 80% on purchasing tractors, rotavators, cultivators, and other modern agricultural implements.",
    "50% तक सब्सिडी": "Up to 50% subsidy",
    "Kisan Credit Card (KCC)": "Kisan Credit Card (KCC)",
    "किसानों को अपनी खेती और घरेलू आवश्यकताओं को पूरा करने के लिए केवल 4% प्रभावी वार्षिक ब्याज दर पर ₹3 लाख तक का आसान ऋण प्रदान किया जाता है।": "Provides easy loan up to ₹3 lakhs to farmers to meet their agricultural and domestic needs at an effective annual interest rate of only 4%.",
    "सिर्फ 4% ब्याज ऋण": "Only 4% interest loan",
    "National Horticulture Mission": "National Horticulture Mission",
    "फलों, सब्जियों, मसालों और फूलों की आधुनिक वैज्ञानिक बागवानी को अपनाने के लिए किसानों को गुणवत्तापूर्ण पौध और सब्सिडी दी जाती है।": "Subsidies and quality saplings are provided to farmers to adopt modern scientific horticulture of fruits, vegetables, spices, and flowers.",
    "बागवानी विशेष अनुदान": "Horticulture Special Grant",

    // Alerts translations
    "🐛 कीट अलर्ट — टिड्डी दल": "🐛 Pest Alert — Locust Swarm",
    "पूर्वी उत्तर प्रदेश के वाराणसी और आसपास के जिलों में टिड्डी दल की भारी सक्रियता देखी गई है। शाम के समय खेतों में तेज़ आवाज़ करें या कीटनाशक का छिड़काव करें।": "Heavy activity of locust swarms has been observed in Varanasi and surrounding districts of Eastern Uttar Pradesh. Make loud noises in fields in the evening or spray pesticides.",
    "पूर्वी UP": "Eastern UP",
    "2 घंटे पहले": "2 hours ago",
    "🌧️ भारी बारिश की चेतावनी": "🌧️ Heavy Rain Warning",
    "मौसम विभाग द्वारा अगले 48 घंटों में भारी गरज के साथ तेज बारिश की चेतावनी जारी की गई है। कृपया कटी हुई फसल को ऊंचे और सुरक्षित स्थान पर ले जाएं, सिंचाई और खाद छिड़काव तुरंत रोक दें।": "Met Department has issued a heavy rain and thunderstorm warning for the next 48 hours. Please move harvested crops to high and safe places, stop irrigation and fertilizer spraying immediately.",
    "UP, Bihar": "UP, Bihar",
    "5 घंटे पहले": "5 hours ago",
    "💰 PM Kisan नई किस्त जारी": "💰 PM Kisan New Installment",
    "प्रधानमंत्री किसान सम्मान निधि (PM Kisan) की 16वीं किस्त सभी पंजीकृत बैंक खातों में ट्रांसफर कर दी गई है। कृपया अपना बैंक बैलेंस चेक करें या सीएससी केंद्र पर जाकर स्टेटस देखें।": "The 16th installment of PM Kisan Samman Nidhi has been transferred to all registered bank accounts. Please check your bank balance or visit CSC center to check status.",
    "राष्ट्रीय": "National",
    "1 दिन पहले": "1 day ago"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('hi');

  // Load language preference from local storage
  useEffect(() => {
    const savedLang = localStorage.getItem('krishi_language') as Language;
    if (savedLang === 'hi' || savedLang === 'en') {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('krishi_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
}
